bdk:
  host: devx3.symphony.com

  bot:
    username: SoufianeBot2
    privateKey:
      path: /Users/soufiane/.symphony/rsa-devx3/privatekey.pem

logging:
  level:
    com.symphony: debug
    org.camunda: debug
    org.camunda.engine.persistence: INFO
