bdk:
  host: devx3.symphony.com

  bot:
    username: workflow-bot
    privateKey:
      path: rsa/privatekey.pem

logging:
  level:
    com.symphony: debug
    org.camunda: debug
    org.camunda.engine.persistence: INFO
