bdk:
  host: devx3.symphony.com
#  agent:
#    host: localhost.symphony.com
#    port: 9443

#  datafeed:
#    version: v2
  bot:
    username: daneel-bot
    privateKey:
      path: rsa/privatekey.pem

logging:
  level:

    com.symphony: DEBUG
    org.camunda: DEBUG
    org.camunda.engine.persistence: INFO

camunda:
  bpm:
    job-execution:
      wait-time-in-millis: 1000
      max-wait: 1000

workflows:
  folder: ./workflows

spring:
  main:
    banner-mode: off
